### ISSUE TITLE
Polygon client example code (both Java and Kotlin) cannot pass authentication

### ISSUE THREAD

**Issue by kebai613** [polygon-io/client-jvm#11]
The two examples in https://github.com/polygon-io/client-jvm/tree/master/sample/src/main/java/io/polygon/kotlin/sdk/sample will always fail with errors like:

Received Message: StatusMessage(ev=status, status=connected, message=Connected Successfully)
Received Message: StatusMessage(ev=status, status=auth_failed, message=authentication failed)
Polygon Disconnected!
Exception in thread "main" java.util.concurrent.CancellationException: ArrayChannel was cancelled
at kotlinx.coroutines.channels.AbstractChannel.cancel(AbstractChannel.kt:639)

However, the same API key always works manually or with my simple Python script.

**Comment by mmoghaddam385** [comment]
Hi @kebai613, thanks for trying out the JVM client! Sorry you're having this issue, unfortunately I can't seem to reproduce the same issue myself.

The sample code connects to a crypto websocket server, is it possible your Polygon.io account is subscribed to a stocks plan but not the "currencies starter" plan?

**Comment by kebai613** [comment]
Hi @mmoghaddam385, you are right. My key only works for stocks. When trying manually, I also used a stock ticker. Once I change the example code, it works now.

Thanks for your quick reply!
