### ISSUE TITLE
Incorrect HttpClient lifetime management

### ISSUE THREAD

**Issue by iulian-radu** [polygon-io/client-jvm#12]
https://github.com/polygon-io/client-jvm/blob/master/src/main/kotlin/io/polygon/kotlin/sdk/rest/PolygonRestClient.kt#L89 is creating and destroying `HttpClient`s in quick succession. 

Here's some code reproducing the problem: 
The CustomProvider:
```


open class CustomProvider
@JvmOverloads
constructor() : HttpClientProvider {
    override fun buildClient(): HttpClient {
        System.out.println("Created client");
        return  HttpClient(Apache) {
            install(WebSockets)
            install(JsonFeature) {
                serializer = KotlinxSerializer(Json.nonstrict)
            }
            engine {
                // this: ApacheEngineConfig
                followRedirects = true
                socketTimeout = 100_000
                connectTimeout = 10_000
                connectionRequestTimeout = 120_000
                customizeClient {
                    // this: HttpAsyncClientBuilder
                    setMaxConnTotal(1)    
                    setMaxConnPerRoute(1)
                    // ...
                }
                customizeRequest {
                    // this: RequestConfig.Builder
                }
            }
        }
    }

    override fun getDefaultRestURLBuilder() =
            URLBuilder(
                    protocol = URLProtocol.HTTPS,
                    port = DEFAULT_PORT
            )
}
```

and a `Scala` consumer of the API
```
    val client = new PolygonRestClient(key, new CustomProvider())
    val referenceClient = client.getReferenceClient

    val params = new SupportedTickersParametersBuilder().tickersPerPage(200).page(1).build()
    val result = referenceClient.getSupportedTickersBlocking(new SupportedTickersParametersBuilder().page(1).tickersPerPage(1).build())
    val numPages = (result.getCount / params.getTickersPerPage) + 1
    val latch = new CountDownLatch(numPages);
    val tickers = mutable.ListBuffer[TickerDTO]()
    val callback = new PolygonRestApiCallback[TickersDTO] {
      override def onError(throwable: Throwable): Unit = {
        latch.countDown()
      }
      override def onSuccess(t: TickersDTO): Unit = {
        println(s"Fetched page ${t.getPage}")
        latch.countDown()
      }
    }

    val startTime = System.nanoTime()
   for {
      i <- 1 to numPages
    } {
      val pars = new SupportedTickersParametersBuilder(params).page(i).build()
      referenceClient.getSupportedTickers(pars, callback)
    }
    latch.await()
    val endTime = System.nanoTime()
    println(s"Took ${(endTime - startTime) / 1000000.0} ms")
```

The expectation was the code would only issue 1 request at a time, due to the following `HttpClient` configurations:
```
                    setMaxConnTotal(1)    
                    setMaxConnPerRoute(1)           
```

The actual output looks like this:
```
Created client
...
... 600 times
...
Created client
Fetched page 2
Fetched page 12
...
...
```

The creation and destruction of `HttpClient`s hugely increases the request latency, as every request must wait for the `HttpClient` creation, which may take 2-4 seconds for some engines. 

I suggest changing the `PolygonRestClient.fetchResult` implementation to 
```
    internal suspend inline fun <reified T> fetchResult(
        urlBuilderBlock: URLBuilder.() -> Unit
    ): T {
        val url = baseUrlBuilder.apply(urlBuilderBlock).build()
        val httpClient = httpClientProvider.buildClient()
        return httpClient.get(url)
    }
```

and the `DefaultJvmHttpClientProvider` to something like:
```
open class DefaultJvmHttpClientProvider
@JvmOverloads
constructor(
    private val engine: HttpClientEngine = OkHttp.create()
) : HttpClientProvider {

    open fun buildEngine(): HttpClientEngine = engine
    val client = HttpClient(buildEngine()) {
            install(WebSockets)
            install(JsonFeature) {
                serializer = KotlinxSerializer(Json.nonstrict)
            }
        }

    override fun buildClient() = client
        

    override fun getDefaultRestURLBuilder() =
        URLBuilder(
            protocol = URLProtocol.HTTPS,
            port = DEFAULT_PORT
        )
}
``` in order to reuse the client.

**Comment by mmoghaddam385** [comment]
Hi @iulian-radu, you bring up a great point, and thanks for the thorough write-up!

I'd like to go in a slightly different direction with your suggestion to fix this though. Instead of essentially caching the HTTPClient in the `HttpClientProvider`, let's have the `PolygonRestClient` do that. I'm mostly suggesting this change because `PolygonWebsocketClient` works on the assumption that `buildClient` returns a new client every time. Plus if anyone is using this library with their own `HttpClientProvider` implementation, they won't have to make any changes to it this way.

Also now that `PolygonWebsocketClient` is no longer closing its HTTPClient after each use, we should have `PolygonWebsocketClient` implement `Closeable` and close its cached HttpClient in the `Close()` method.

Please feel free to make a PR with these changes and request me as a reviewer if you'd like, otherwise I can try to get to it myself some time next week.

**Comment by iulian-radu** [comment]
You're right, @mmoghaddam385 ! It's probably better to implement your suggestion. 
I'll give it a spin tonight and see what I end up with.

**Comment by justinpolygon** [comment]
Hello, I'm going to close this out since we have significantly changed the way things work since 2021. In addition to updating Ktor. So, I'm going to close this and the corresponding PR https://github.com/polygon-io/client-jvm/pull/13 and we'll take a another look to see if we can improve things.
