### ISSUE TITLE
Bug: JVM client for Universal Snapshot

### ISSUE THREAD

**Issue by upMKuhn** [polygon-io/client-jvm#151]
Hello :) 

I found a new bug in the client. The query parameter should be ticker.any_of instead of tickers.any_of in the getSnapshot client.

Could you please take a look?

**Comment by HunterL** [comment]
This issue has been fixed in #152 and released as part of [v5.1.1](https://github.com/polygon-io/client-jvm/releases/tag/v5.1.1).

Thank you for the report!
