### ISSUE TITLE
java example using the spring boot

### ISSUE THREAD

**Issue by tarunsyfe** [polygon-io/client-jvm#16]
Hi needed the support for java example for spring boot please assist in that

**Comment by leodev87** [comment]
+1

**Comment by MDJm8fintech** [comment]
+1

**Comment by vadims-grusas** [comment]
Here is a pull request with a fix. https://github.com/polygon-io/client-jvm/pull/30
Use it until it is merged. 
I haven`t found any other solution on how to use it together with spring

**Comment by justinpolygon** [comment]
Hey, closing this out since this has been fixed via https://github.com/polygon-io/client-jvm/pull/30 and someone has confirmed it's working via https://github.com/polygon-io/client-jvm/pull/30#issuecomment-1103433639.
