### ISSUE TITLE
There is no volume weighted average price in AggregateDTO 

### ISSUE THREAD

**Issue by Alexander-Karpovich** [polygon-io/client-jvm#17]
Polygon in this https://polygon.io/docs/get_v2_aggs_ticker__stocksTicker__range__multiplier___timespan___from___to__anchor endpoint response has field for volume weighted average price named "vw". Could you add it to AggregateDTO?

**Comment by mmoghaddam385** [comment]
You're right! Thanks for pointing this out, I've added `volumeWeightedAveragePrice` in release v1.2.2
