### ISSUE TITLE
Duplicate class error 

### ISSUE THREAD

**Issue by KumarRupesh** [polygon-io/client-jvm#29]
Hi,
After I added below dependencies in my application build.gradle

    implementation 'com.github.polygon-io:client-jvm:v2.0.0'
    implementation 'com.tylerthrailkill.helpers:pretty-print:v2.0.7'
    implementation 'io.ktor:ktor-client-core:1.5.3'
    implementation 'io.ktor:ktor-client-cio-jvm:1.5.3

I started getting below error. Could you please check and advise.

Duplicate class javax.activation.MimetypesFileTypeMap found in modules activation-1.1.jar (javax.activation:activation:1.1) and javax.activation-1.2.0.jar (com.sun.activation:javax.activation:1.2.0)
Duplicate class javax.activation.ObjectDataContentHandler found in modules activation-1.1.jar (javax.activation:activation:1.1) and javax.activation-1.2.0.jar (com.sun.activation:javax.activation:1.2.0)
Duplicate class javax.activation.SecuritySupport found in modules activation-1.1.jar (javax.activation:activation:1.1) and javax.activation-1.2.0.jar (com.sun.activation:javax.activation:1.2.0)
Duplicate class javax.activation.SecuritySupport$1 found in modules activation-1.1.jar (javax.activation:activation:1.1) and javax.activation-1.2.0.jar (com.sun.activation:javax.activation:1.2.0)
Duplicate class javax.activation.SecuritySupport$2 found in modules activation-1.1.jar (javax.activation:activation:1.1) and javax.activation-1.2.0.jar (com.sun.activation:javax.activation:1.2.0)
Duplicate class javax.activation.SecuritySupport$3 found in modules activation-1.1.jar (javax.activation:activation:1.1) and javax.activation-1.2.0.jar (com.sun.activation:javax.activation:1.2.0)
Duplicate class javax.activation.SecuritySupport$4 found in modules activation-1.1.jar (javax.activation:activation:1.1) and javax.activation-1.2.0.jar (com.sun.activation:javax.activation:1.2.0)
Duplicate class javax.activation.SecuritySupport$5 found in modules activation-1.1.jar (javax.activation:activation:1.1) and javax.activation-1.2.0.jar (com.sun.activation:javax.activation:1.2.0)
Duplicate class javax.activation.URLDataSource found in modules activation-1.1.jar (javax.activation:activation:1.1) and javax.activation-1.2.0.jar (com.sun.activation:javax.activation:1.2.0)
Duplicate class javax.activation.UnsupportedDataTypeException found in modules activation-1.1.jar (javax.activation:activation:1.1) and javax.activation-1.2.0.jar (com.sun.activation:javax.activation:1.2.0)

**Comment by mmoghaddam385** [comment]
With the dependency updates in the most recent releases, this issue should be resolved. Please re-open if this is still a problem
