### ISSUE TITLE
background thread remains active

### ISSUE THREAD

**Issue by jbaron** [polygon-io/client-jvm#31]
I have been using this lib to access polygon.io from my algo-trading platform (roboquant) and it works great of far (the integration is just a small prototype so far). But I noticed that somewhere remains one or more threads active since the main will not normally end.

I'm using the `PolygonRestClient` with default http provider and `client.getAggregatesBlocking` to get some data. When I checked your code seem to be using `use()` under the hood, so that should close the HttpClient after use. Is there anything else that is running on the background that I need to stop manually ?

My prototype code (very small) can be found here: https://github.com/neurallayer/roboquant/blob/main/roboquant-extra/src/polygon/PolygonHistoricFeed.kt

P.S _roboquant_ is open source, so if you want to check it out: https://roboquant.org

**Comment by mmoghaddam385** [comment]
Hi @jbaron , can you confirm if this is still an issue? This may have been fixed by some of the dependencies that have been updated since this was reported.

**Comment by jbaron** [comment]
@mmoghaddam385 Thanks for getting back to me. Just did a quick re-check and indeed there are no more active threads lingering and my tests (https://roboquant.org) end as expected. 

So thanks and of course also this issue can be closed.
