### ISSUE TITLE
How to get next page from response object of PolygonReferenceClient.getSupportedTickers()

### ISSUE THREAD

**Issue by wangtieqiao** [polygon-io/client-jvm#33]
Per ApI spec 
`suspend fun PolygonReferenceClient.getSupportedTickers(
    params: SupportedTickersParameters
): TickersDTO {}`

will return Ticker's DTO object that contains next_url string to be used grab next page, how can I use it? 

in release v1.3.0, the `SupportedTickersParameters` object used to contain a `page` field, so you can repleately call 

` PolygonReferenceClient.getSupportedTickers(
    params: SupportedTickersParameters
): TickersDTO `

 method with same params object with increase page by +1. 

The new API return object give a next_url which contains a cursor field, but not sure how to use it with latest release ....

**Comment by mmoghaddam385** [comment]
Hi @wangtieqiao , unfortunately there isn't a great way to page through responses with the `next_url` field directly through the library at the moment. This is something I'll actively be working on in the next couple days, and will hopefully have it out in a release by the end of the week. Sorry for the inconvenience

**Comment by mmoghaddam385** [comment]
It's now the end of the week so I wanted to give a quick update on this: We've been making good progress but aren't quite ready to make a release that addresses this concern yet. 

We've proved the concept of iterators to handle pagination under the hood in PR #42 and are in the process of replacing deprecated APIs with newer ones so we need a bit more time to flesh it all out. 

If you have any comments or concerns with the iterator approach to pagination please let me know 👍

**Comment by mmoghaddam385** [comment]
Hi @wangtieqiao , iterator changes have been finished and released in [v4.1.0](https://github.com/polygon-io/client-jvm/releases/tag/v4.1.0)! You can now iterate over a list of tickers and the SDK will handle pagination under the hood for you by using the `PolygonReferenceClient.listSupportedTickers(...)` function. See [here](https://github.com/polygon-io/client-jvm#pagination) for some more details around pagination in the SDK. 

Let me know if you have any questions about any of this.

**Comment by wangtieqiao** [comment]
Thanks, it looks great @mmoghaddam385 but the new release seems not available ref to ticket #63

**Comment by jbaron** [comment]
Great library, using it in my [roboquant](roboquant.org) project and easy to use.

Now I'm trying the new pagination feature where I want to retrieve all available active stocks (included code snippet how I do it). 

But I have one question. I assume the limit size I can define in the SupportedTickersParameters is the page limit size? I would still get back all the stocks if I continue to iterate over the sequence, correct? 

 ```kotlin
internal fun availableAssets(client: PolygonRestClient): List<Asset> {
    val assets = mutableListOf<Asset>()
    val params = SupportedTickersParameters(
        limit = 1000,
        market = "stocks",
        sortBy = "ticker",
        sortDescending = false,
        activeSymbolsOnly = true,
    )

    client.referenceClient.listSupportedTickers(params).asSequence().forEach {
        val asset = it.toAsset()
        assets.addNotNull(asset)
    }

    return assets
}
```

P.S Seem I'm hitting some limitations of the free API so I cannot validate this right now, but I get more than 1000 assets back.

**Comment by mmoghaddam385** [comment]
Hi @jbaron, I'm happy to hear you like the library :) 

To answer your question: Yes, `limit` affects the size of each page that the API returns. If you iterate over the whole sequence it will make as many requests as it needs to get the full set of stock tickers.

**Comment by wangtieqiao** [comment]
Thank you @mmoghaddam385, everything good now
