### ISSUE TITLE
Could you please update ktor version. 1.3.0 doesn't close connections.

### ISSUE THREAD

**Issue by belarusrulez** [polygon-io/client-jvm#5]
Could you please update ktor version. 1.3.0 doesn't close connections.
I've tested 1.3.1 it does.
issue was found using this client in java. max connections I've had was 1500+

![image](https://user-images.githubusercontent.com/1071191/85806915-3e875f00-b705-11ea-9978-474d743db211.png)

**Comment by mmoghaddam385** [comment]
Hey @belarusrulez, thanks for letting me know about this problem! I just created a new release with the updated ktor dependency (1.0.1), let me know if you have any other questions or suggestions for the SDK. Also, feel free to fork and make PRs in the future!
