### ISSUE TITLE
Incorrect mapping of "lastTrade.exchange" in the stocks snapshot API response

### ISSUE THREAD

**Issue by v3rm0n** [polygon-io/client-jvm#93]
In the code, `e` is specified as an exchangeId: https://github.com/polygon-io/client-jvm/blob/master/src/main/kotlin/io/polygon/kotlin/sdk/rest/stocks/Snapshots.kt#L90

In the API docs it is `x`, as it is in the actual API response https://polygon.io/docs/stocks/get_v2_snapshot_locale_us_markets_stocks_tickers

**Comment by justinpolygon** [comment]
Hey @v3rm0n, thanks for the heads up. I'll check this out.

**Comment by v3rm0n** [comment]
Any plans on fixing this?

**Comment by v3rm0n** [comment]
Anything? @justinpolygon

**Comment by justinpolygon** [comment]
Sorry @v3rm0n. I missed this. It's merged now. Thanks for catching this.
